---
name: 🐧 Test sh (Linux)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: ☑️ ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
        with:
          scandir: "./doc/install.sh"

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [shellcheck]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - name: ⚙️ Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh
      - name: ⚙️ Test
        run: sh ./doc/install.sh
      - name: ⚙️ Load
        run: |
          source ~/.zshrc
          cat ~/.zshrc
          echo "zsh version: $ZSH_VERSION"
        shell: zsh {0}
