---
name: 🐧 Test sh (Linux)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: ☑️ ShellCheck
        uses: ludeeus/action-shellcheck@6d3f514f44620b9d4488e380339edc0d9bbe2fba
        with:
          scandir: "./doc/install.sh"

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [shellcheck]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: ⚙️ Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh
      - name: ⚙️ Test
        run: sh ./doc/install.sh
      - name: ⚙️ Load
        run: |
          source ~/.zshrc
          echo "zsh version: $ZSH_VERSION"
          echo "zsh
        shell: zsh {0}
